common:
  property: common value
some:
  property: common value

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: "/admin/health"
    status-page-url-path: "/admin/info"
