info:
  year: 2018
  company: "Vattenfall"

server:
  port: 9100

spring:
  jackson:
    serialization:
      indent-output: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      jmx:
        enabled: false
      graphite:
        enabled: false

---

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/${POSTGRES_DB:warehouse}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:sprio}"
  jpa:
    hibernate:
      ddl-auto: "validate"
